### ISSUE TITLE
Site is not responsive

### ISSUE THREAD

**Issue by takshch** [Real-Dev-Squad/website-learn#10]
# Description 
Site is not responsive

#  Screenshot
![image](https://user-images.githubusercontent.com/26649558/120889758-3e355a80-c61c-11eb-9e70-e9dc6e034552.png)

**Comment by apuchakraborty** [comment]
assign me

**Comment by eduardarakelyan** [comment]
Hello,
So the issue is that the site is not responsive on mobile?

**Comment by takshch** [comment]
@eduardarakelyan Yes, In mobile, Layout for videos is not responsive.

**Comment by eduardarakelyan** [comment]
Alright I’ll double check.

**Comment by akankshadharkar** [comment]
https://github.com/Real-Dev-Squad/website-learn/pull/7 should fix this
