### ISSUE TITLE
Modal window to choose user preference 

### ISSUE THREAD

**Issue by rajakvk** [Real-Dev-Squad/website-learn#16]
In home page, on page load, open a modal window with title "What is your preference?" and options, "Articles, Audio/Video" as shown in the below image.

On selecting any one of the options, store that value in browser localStorage for later use.
<img width="580" alt="Screen Shot 2021-06-27 at 9 14 28 PM" src="https://user-images.githubusercontent.com/120031/123550767-c080ec80-d78c-11eb-8a1e-3e5dba8c44fd.png">

**Comment by SBagaria2710** [comment]
Task Completed by @rajakvk
