### ISSUE TITLE
Comparison between Vue3 vs Nuxtjs

### ISSUE THREAD

**Issue by aakankshadhurandhar** [Real-Dev-Squad/website-learn#61]
### NuxtJS
> ## Pros

-  SEO improvement: We need this feature because our learning site is a public web application that includes social sharing features of our progress.
- Generates own router structure based on the folder structure. It is easier and faster to work with.
- For larger applications: Pre-configured folder structure for middlewares, and plugins.
- Good data fetching pattern asyncData and fetch. 

> ## Cons
- As automatic routing so less controllable and manageable.

### Vue3

> ## Pros
- Routing can be controlled and manageable. 
-  Composition API
     - Better organization, Sharing/reusing the code
     - Multiple root elements can be used now inside the template.

> ## Cons
- For SPA only 
- Manual routing and folder structure Can get complex over time.
- Vue.js applications contain the App.vue file as a core root component.
- TTFB(Time to first bite) will be more.

**Comment by yesyash** [comment]
Adding to the points aakanksha mentioned: 

### Nuxt JS

> Cons

- No support for Vue 3, only a beta version is out.
- Typescript support for the current server engine is not great, it will change with the new Nuxt3 stable release.
