### ISSUE TITLE
Pre-commit hook for linting,prettier and test-cases 

### ISSUE THREAD

**Issue by aakankshadhurandhar** [Real-Dev-Squad/website-learn#68]
Use [Husky ](https://typicode.github.io/husky/#/)Or [pre-commit ](https://pre-commit.com/) to set up pre-commit hook for the repo .

**Comment by Gautam-Arora24** [comment]
Since , I am new to husky and would like to learn more about it, Therefore Interested in this issue :)

**Comment by samarpan1738** [comment]
@Gautam-Arora24 Loop me in as well. I'm interested in learning this

**Comment by SBagaria2710** [comment]
Merged to main branch.

PR: https://github.com/Real-Dev-Squad/website-learn/pull/76
